library(dplyr)
library(magrittr)
library(reshape2)
library(stringr)
library(networkD3)
library(shiny)
library(shinyWidgets)
library(htmlwidgets)
library(highcharter)
library(r2d3)
source('counter_data_new.R',encoding = 'UTF-8')
source('counter_server.R',encoding = 'UTF-8')
source('counter_ui.R',encoding = 'UTF-8')

shinyApp(ui = ui, server = server)
